name: Trigger Render Cron

on:
  schedule:
    - cron: "*/15 * * * *"

  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Call Render API
        run: |
          curl "$CRON_URL"
        env:
          CRON_URL: ${{ secrets.CRON_URL }}